name: LeetCode Stats

on:
  schedule:
    - cron: "0 0 * * 1"  # Runs every Monday
  workflow_dispatch:    # Allows manual trigger

jobs:
  update-readme:
    name: Update LeetCode Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LEETCODE: "True"
          LEETCODE_USERNAME: "your_leetcode_username"
